services:
  db:
    container_name: postgres_container_be
    image: postgres
    environment:

      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

volumes:
  db:

networks:
  db:
    driver: bridge